title: Eric Nost
logo: /assets/img/Nost.jpg
description: Associate Professor of Geography, Environment, and Geomatics | University of Guelph
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
